
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: build
  jobs:
  - job: BuildJob
    displayName: buildjob
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
    - task: CmdLine@2
      inputs:
        script: 'npm install'
    - task: CmdLine@2
      inputs:
        script: 'npm run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build'
        ArtifactName: 'Build'
        publishLocation: 'Container'
- stage: deploy
  displayName: deploy
  jobs:
  - job: deployJob
    displayName: deployjob
    steps: 
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'Build'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'forntbuild'
        sourceFolder: '$(Build.ArtifactStagingDirectory)/Build'
        contents: '**'
        targetFolder: '/tmp/copyfolder'
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'forntbuild'
        runOptions: 'commands'
        commands: |
          sudo cp -r /tmp/copyfolder/* /var/www/html
          sudo systemctl restart nginx
        readyTimeout: '20000'